name: dart_lambda
description: A sample lambda application.
version: 1.0.0

environment:
  sdk: ^3.0.7

dependencies:
  retry: ^3.1.0
  http: ^0.13.3
  aws_lambda_dart_runtime: ^1.0.3+2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
